FROM sameersbn/postgresql:9.5-2

ENV DB_USER: scrumuser
ENV DB_NAME: 'scrum'
ENV DB_EXTENSION: 'adminpack,unaccent,pg_trgm'
ENV REPLICATION_USER: repluser
ENV USERMAP_UID: '5001'
ENV USERMAP_GID: '5001'
ENV PG_PASSWORD: pgpass1234
ENV DB_PASS: pass1234
ENV REPLICATION_PASS: replpass1234
